CREATE TABLE USUARIO (
  USU_COD INT AUTO_INCREMENT PRIMARY KEY,
  USU_USUARIO VARCHAR(50) NOT NULL,
  USU_SENHA_HASH VARCHAR(255) NOT NULL,
  USU_STATU ENUM('Ativo', 'Desativado', 'Pendente') NOT NULL DEFAULT 'Pendente'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE FORNECEDOR (
  FOR_COD INT AUTO_INCREMENT PRIMARY KEY,
  FOR_CNPJ VARCHAR(14) NOT NULL UNIQUE,
  FOR_RAZAO_SOCIAL VARCHAR(140) NOT NULL,
  FOR_ENDERECO VARCHAR(150) NOT NULL,
  FOR_TELEFONE VARCHAR(11) NOT NULL,
  FOR_RESPONSAVEL VARCHAR(40) NOT NULL  
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci; 

CREATE TABLE CLIENTE (
  CLI_COD INT AUTO_INCREMENT PRIMARY KEY,
  CLI_CPF_CNPJ VARCHAR(14) NOT NULL UNIQUE,
  CLI_NOME VARCHAR(100) NOT NULL,
  CLI_TELEFONE VARCHAR(11)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE PEDIDO (
  PED_COD INT AUTO_INCREMENT PRIMARY KEY,
  PED_CLI_COD INT NOT NULL,
  PED_FOR_COD INT NOT NULL,
  PED_NUMERO_CHAMADO VARCHAR(7) UNIQUE,
  PED_PRODUTO VARCHAR(100),
  PED_QUANTIDADE INT,
  PED_PEDIDO_DATA DATE,
  PED_VALOR DECIMAL(15, 2),
  PED_STATUS_PEDIDO ENUM('Resolvido', 'Pendente', 'Pendente') NOT NULL DEFAULT 'Pendente',
  FOREIGN KEY (PED_CLI_COD) REFERENCES CLIENTE(CLI_COD),
  FOREIGN KEY (PED_FOR_COD) REFERENCES FORNECEDOR(FOR_COD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


CREATE TABLE ORCAMENTO (
  ORC_COD INT AUTO_INCREMENT PRIMARY KEY,
  ORC_PED_COD INT NOT NULL,
  ORC_FOR_COD INT NOT NULL,
  ORC_CLI_COD INT NOT NULL,
  ORC_NOME_ARQUIVO VARCHAR(255),
  ORC_HORCAMENTO_PDF VARCHAR(255),
  ORC_STATUS_GESTAO ENUM('Aprovado', 'Reprovado', 'Pendente') NOT NULL DEFAULT 'Pendente',
  FOREIGN KEY (ORC_PED_COD) REFERENCES PEDIDO(PED_COD),
  FOREIGN KEY (ORC_FOR_COD) REFERENCES FORNECEDOR(FOR_COD),
  FOREIGN KEY (ORC_CLI_COD) REFERENCES CLIENTE(CLI_COD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Despejando dados para a tabela = USUARIO

INSERT INTO USUARIO (USU_USUARIO, USU_SENHA_HASH, USU_STATU) VALUES
('kassio', '310ea5e7934323b2cf1ef31fca2aa2b1', 1);

INSERT INTO FORNECEDOR (FOR_CNPJ, FOR_RAZAO_SOCIAL, FOR_ENDERECO, FOR_TELEFONE, FOR_RESPONSAVEL) VALUES
('24111769000145', 'IMAX TECNOLOGIA LTDA', 'RUA 250, QD 34 LT 07 SETOR COIMBRA', '62993093392', 'RICARDO'); 

INSERT INTO CLIENTE (CLI_CPF_CNPJ, CLI_NOME, CLI_TELEFONE) VALUES
('33636838000397', 'GRUPO NASA GOIANIA', '6232408085');